### ISSUE TITLE
Add possibility to move watermark within HVTView 

### ISSUE THREAD

**Issue by rozd** [HorizonCamera/HorizonSDK-iOS#2]
It would be great to have possibility to move watermark in HVTView and have possibility to place some button at right bottom corner over the view.

**Comment by stelabouras** [comment]
Thanks for the feedback Max!

We do plan to add the ability to place Horizon SDK watermark in distinct locations in an HVTView with the next update of the library, so that you can place a button at the right bottom corner of the view if you want.

**Comment by stelabouras** [comment]
Hey Max! The feature has been added. 

You can use the `watermarkPosition` property of the `HVTView` to move the watermark in one of the four corners of the view. You can read more on [Horizon SDK documentation](https://horizon.camera/static/sdk/docs/Classes/HVTView.html#//api/name/watermarkPosition).

**Comment by rozd** [comment]
Thanks!
