### ISSUE TITLE
Sample App

### ISSUE THREAD

**Issue by ncwarren** [HorizonCamera/HorizonSDK-iOS#3]
Is there any instructions for using the sample apps? I can't change Bundle ID without a crash, and can't create a provisioning profile for that bundle ID

**Comment by stelabouras** [comment]
The API keys used in the sample apps are associated with their respective Bundle Identifier, so if you change them the sample apps will crash with a `App bundle id does not match` exception. Also, the bundle ids of the sample apps are not meant to be used for deploying those apps to the App Store, just to get those apps to run in your test devices.

If you want to just build the sample apps to your test device, you can do so by using the "Personal Team" value from the "Team" option of the General tab of each sample app Target.

![app-signing](https://user-images.githubusercontent.com/49122/47265491-5c182480-d531-11e8-8d22-5cc0cd406ec5.png)

If you are interested in trying out Horizon SDK, send us an email at developers@horizon.camera and we will provide you with a 30 trial key for the platform(s) of your choice (iOS or Android).

Thank you.

**Comment by bluedream0829** [comment]
I'm currently integrating your SDK into my application, and I encountered an issue when changing the bundle ID. Could you please provide guidance on how to obtain the SDK for use in a live app environment?

Additionally, I'd like to inquire about the subscription options for accessing the SDK. Are there any subscription plans available, or is it provided for free?

Thank you for your assistance.
