### ISSUE TITLE
Camera live view is not full screen if setting AVCaptureDeviceTypeBuiltInTripleCamera device type

### ISSUE THREAD

**Issue by navrozhuda** [HorizonCamera/HorizonSDK-iOS#4]

**Comment by stelabouras** [comment]
Hello @navrozhuda! 

Can you provide more information regarding this issue? 

* Do you have a screenshot highlighting the problem?
* Is the `HVTView` (`preview`) size controlled by storyboard constraints or is its frame set programmatically?
* Do you experience the same issue if the device type is set to `AVCaptureDeviceTypeBuiltInDualCamera` or `AVCaptureDeviceTypeBuiltInDualWideCamera`?
